[project]
name = "llama-stack-provider-ragas"
version = "0.1.0"
description = "Ragas evaluation as an out-of-tree Llama Stack provider"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-stack",
    "ragas",
]

[project.optional-dependencies]
distro = ["opentelemetry-api", "opentelemetry-exporter-otlp", "aiosqlite", "ollama", "uvicorn"]
dev = ["pytest", "pytest-asyncio", "pytest-cov", "black", "isort", "ipykernel", "rich"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
pythonpath = ["src"]
addopts = "-v"
log_cli = true
log_cli_level = "INFO"
markers = [
    "integration_test: Integration tests that require a running Llama Stack server",
]